# These are supported funding model platforms

custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://curseforge.com/minecraft/modpacks/ubiclient', 'https://github.com/ubionexd', 'https://bit.ly/ubionedc']
